module ApplicationHelper

  def us_states
      [
        {:state => '', :abrv =>  ''},
        {:state => 'Alabama', :abrv =>  'AL'},
        {:state => 'Alaska', :abrv =>  'AK'},
        {:state => 'Arizona', :abrv =>  'AZ'},
        {:state => 'Arkansas', :abrv =>  'AR'},
        {:state => 'California', :abrv =>  'CA'},
        {:state => 'Colorado', :abrv =>  'CO'},
        {:state => 'Connecticut', :abrv =>  'CT'},
        {:state => 'Delaware', :abrv =>  'DE'},
        {:state => 'District of Columbia', :abrv =>  'DC'},
        {:state => 'Florida', :abrv =>  'FL'},
        {:state => 'Georgia', :abrv =>  'GA'},
        {:state => 'Hawaii', :abrv =>  'HI'},
        {:state => 'Idaho', :abrv =>  'ID'},
        {:state => 'Illinois', :abrv =>  'IL'},
        {:state => 'Indiana', :abrv =>  'IN'},
        {:state => 'Iowa', :abrv =>  'IA'},
        {:state => 'Kansas', :abrv =>  'KS'},
        {:state => 'Kentucky', :abrv =>  'KY'},
        {:state => 'Louisiana', :abrv =>  'LA'},
        {:state => 'Maine', :abrv =>  'ME'},
        {:state => 'Maryland', :abrv =>  'MD'},
        {:state => 'Massachusetts', :abrv =>  'MA'},
        {:state => 'Michigan', :abrv =>  'MI'},
        {:state => 'Minnesota', :abrv =>  'MN'},
        {:state => 'Mississippi', :abrv =>  'MS'},
        {:state => 'Missouri', :abrv =>  'MO'},
        {:state => 'Montana', :abrv =>  'MT'},
        {:state => 'Nebraska', :abrv =>  'NE'},
        {:state => 'Nevada', :abrv =>  'NV'},
        {:state => 'New Hampshire', :abrv =>  'NH'},
        {:state => 'New Jersey', :abrv =>  'NJ'},
        {:state => 'New Mexico', :abrv =>  'NM'},
        {:state => 'New York', :abrv =>  'NY'},
        {:state => 'North Carolina', :abrv =>  'NC'},
        {:state => 'North Dakota', :abrv =>  'ND'},
        {:state => 'Ohio', :abrv =>  'OH'},
        {:state => 'Oklahoma', :abrv =>  'OK'},
        {:state => 'Oregon', :abrv =>  'OR'},
        {:state => 'Pennsylvania', :abrv =>  'PA'},
        {:state => 'Puerto Rico', :abrv =>  'PR'},
        {:state => 'Rhode Island', :abrv =>  'RI'},
        {:state => 'South Carolina', :abrv =>  'SC'},
        {:state => 'South Dakota', :abrv =>  'SD'},
        {:state => 'Tennessee', :abrv =>  'TN'},
        {:state => 'Texas', :abrv =>  'TX'},
        {:state => 'Utah', :abrv =>  'UT'},
        {:state => 'Vermont', :abrv =>  'VT'},
        {:state => 'Virginia', :abrv =>  'VA'},
        {:state => 'Washington', :abrv =>  'WA'},
        {:state => 'West Virginia', :abrv =>  'WV'},
        {:state => 'Wisconsin', :abrv =>  'WI'},
        {:state => 'Wyoming', :abrv =>  'WY'}
      ]
  end



end
