class Personal < ActiveRecord::Base
  attr_accessible       :first_name,
                        :last_name,
                        :middle_initial,
                        :date_of_birth,
                        :age,
                        :ss_number,
                        :gender,
                        :address,
                        :city,
                        :state,
                        :zip_code,
                        :home_phone,
                        :cell_phone,
                        :work_phone,
                        :email_address,
                        :marital_status,
                        :ethnicity,
                        :race,
                        :employer,
                        :employment_status,
                        :occupation,
                        :work_address,
                        :number_of_dependents,
                        :employer_phone,
                        :employer_city,
                        :employer_state,
                        :employer_zipcode,
                        :relationship_to_responsible_party,
                        :referred_by,
                        :form_id

  belongs_to :form

end
